---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcdtrialtwo
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcdtrialtwo
  targetNamespace: default

